### ISSUE TITLE
Creation appli agular

### ISSUE THREAD

**Issue by LPA2-Automne2016** [LPA2-Automne2016/lp71-projet-front-P2019#1]
Installer angular ( version 6 !!! pas la 7 )
Astuce: si proxy, npm config set https-proxy https://proxy.utbm.fr:3128

créer une nouvelle application vide `ng new store --directory .`

mettre en place netlify ( attention au nom de dossier dans lequel est généré l'appli)
https://levlaz.org/deploying-an-angular-6-application-to-netlify/

poster ici le lien vers votre site sous netlify

**Comment by macdrien** [comment]
Adrien Bouyssou

Netlify: https://naughty-sammet-362d3b.netlify.com/

**Comment by RemiPapillier** [comment]
Rémi Papillier

Netlify: 
https://pensive-northcutt-92b57a.netlify.com/

**Comment by vareversat** [comment]
Valentin REVERSAT

https://netlify.kebab-hurlant.fr/

**Comment by Joan68** [comment]
Joan Frey

Netlify app :
https://boring-sammet-32a8dd.netlify.com/

**Comment by AppliNH** [comment]
Thomas MARTIN

[C'est par ici](https://elegant-mcclintock-ebb8c8.netlify.com/)

**Comment by Oxyh** [comment]
Adrien Devaux

https://musing-euclid-a786ee.netlify.com/

**Comment by Swyfee** [comment]
Thibaut ROUSSEAUX
[Netifly](https://modest-neumann-1b106a.netlify.com/)

**Comment by BHemez** [comment]
[Netifly](https://gracious-borg-c63481.netlify.com/)

**Comment by PantchoL** [comment]
Lucas Pantchenko

[Netlify](https://condescending-aryabhata-6bb32a.netlify.com/index.html)

**Comment by MPantcho** [comment]
PANTCHENKO Mathieu

https://objective-liskov-e78c43.netlify.com/

**Comment by vgalin** [comment]
Vincent G
[Netlify](https://goofy-wilson-c0ec99.netlify.com/)

**Comment by MohamedCA2018** [comment]
Mohamed El Guendouz 

https://priceless-wiles-10396d.netlify.com

**Comment by S-HENR** [comment]
Séraphin Henry

[Netlify](https://elegant-jepsen-2281bc.netlify.com/)

**Comment by Clau-G** [comment]
Claudia G.

[Netlify](https://jovial-ptolemy-d819db.netlify.com/)

**Comment by Julienm25** [comment]
Julien Mauvais
https://lp71-store.netlify.com/

**Comment by GRazafy** [comment]
Gabriel Razafindratsima

[Netify](https://musing-kirch-a66ed5.netlify.com/)

**Comment by L-Co-P** [comment]
Loann Peurey
https://vigilant-golick-fa4842.netlify.com/

**Comment by MangeTonChat** [comment]
Valentin QUIGUER
https://vigilant-noether-455710.netlify.com/

**Comment by Holdem67** [comment]
Antoine Mougin
https://cocky-pare-50a656.netlify.com/

**Comment by fhenriot** [comment]
Fabien Henriot : 
https://angular-dreamy-euler.netlify.com/

**Comment by admo-1** [comment]
Adil Mohammad

[Netlify](https://infallible-rosalind-10be66.netlify.com/)

**Comment by vtison** [comment]
Victor Tison

https://flamboyant-wilson-3e0d45.netlify.com/

**Comment by Skaopap** [comment]
Benjamin Thominet

https://silly-booth-487544.netlify.com/

**Comment by LPA2-Automne2016** [comment]
Bon boulot tout le monde !
